"""empty message

Revision ID: b7a054b546a9
Revises: 0aa2fa812248
Create Date: 2016-06-13 11:33:27.896491

"""

# revision identifiers, used by Alembic.
revision = 'b7a054b546a9'
down_revision = '0aa2fa812248'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
